import {
  alandur2Img,
  alandurgreyImg,
  alandurImg,
  ambattur2Img,
  ambatturgreyImg,
  ambatturImg,
  aminjikarai2Img,
  aminjikaraigreyImg,
  aminjikaraiImg,
  egmore2Img,
  egmoregreyImg,
  egmoreImg,
  guindy2Img,
  guindygreyImg,
  guindyImg,
  madhavaram2Img,
  madhavaramgreyImg,
  madhavaramImg,
  maduravoyal2Img,
  maduravoyalgreyImg,
  maduravoyalImg,
  mambalam2Img,
  mambalamgreyImg,
  mambalamImg,
  mylapore2Img,
  mylaporegreyImg,
  mylaporeImg,
  perambur2Img,
  peramburgreyImg,
  peramburImg,
  purasaiwakkam2Img,
  purasaiwakkamgreyImg,
  purasaiwakkamImg,
  sholinganallur2Img,
  sholinganallurgreyImg,
  sholinganallurImg,
  thiruvottiyur2Img,
  thiruvottiyurgreyImg,
  thiruvottiyurImg,
  tondiarpet2Img,
  tondiarpetgreyImg,
  tondiarpetImg,
  velacherry2Img,
  velacherrygreyImg,
  velacherryImg
} from '../../../assets/images/map';

export const DistrictData = [
  {
    id: 0,
    name: 'districts.Thiruvottiyur',
    blueImage: thiruvottiyurImg,
    greyImage: thiruvottiyurgreyImg,
    yellowImage: thiruvottiyur2Img,
    styleBlue: 'Thiruvottiyur',
    styleYellow: 'Thiruvottiyur2',
    title: 'Thiruvottiyur'
  },
  {
    id: 1,
    name: 'districts.Madhavaram',
    blueImage: madhavaramImg,
    greyImage: madhavaramgreyImg,
    yellowImage: madhavaram2Img,
    styleBlue: 'Madhavaram',
    styleYellow: 'Madhavaram2',
    title: 'Madhavaram'
  },
  {
    id: 2,
    name: 'districts.Perambur',
    blueImage: peramburImg,
    greyImage: peramburgreyImg,
    yellowImage: perambur2Img,
    styleBlue: 'Perambur',
    styleYellow: 'Perambur2',
    title: 'Perambur'
  },
  {
    id: 3,
    name: 'districts.Tondiarpet',
    blueImage: tondiarpetImg,
    greyImage: tondiarpetgreyImg,
    yellowImage: tondiarpet2Img,
    styleBlue: 'Tondiarpet',
    styleYellow: 'Tondiarpet2',
    title: 'Tondiarpet'
  },
  {
    id: 4,
    name: 'districts.Ambattur',
    blueImage: ambatturImg,
    greyImage: ambatturgreyImg,
    yellowImage: ambattur2Img,
    styleBlue: 'Ambattur',
    styleYellow: 'Ambattur2',
    title: 'Ambattur'
  },
  {
    id: 5,
    name: 'districts.Aminjikarai',
    blueImage: aminjikaraiImg,
    greyImage: aminjikaraigreyImg,
    yellowImage: aminjikarai2Img,
    styleBlue: 'Aminjikarai',
    styleYellow: 'Aminjikarai2',
    title: 'Aminjikarai'
  },
  {
    id: 6,
    name: 'districts.Purasaiwakkam',
    blueImage: purasaiwakkamImg,
    greyImage: purasaiwakkamgreyImg,
    yellowImage: purasaiwakkam2Img,
    styleBlue: 'Purasaiwakkam',
    styleYellow: 'Purasaiwakkam2',
    title: 'Purasaiwakkam'
  },
  {
    id: 7,
    name: 'districts.Egmore',
    blueImage: egmoreImg,
    greyImage: egmoregreyImg,
    yellowImage: egmore2Img,
    styleBlue: 'Egmore',
    styleYellow: 'Egmore2',
    title: 'Egmore'
  },
  {
    id: 8,
    name: 'districts.Maduravoyal',
    blueImage: maduravoyalImg,
    greyImage: maduravoyalgreyImg,
    yellowImage: maduravoyal2Img,
    styleBlue: 'Maduravoyal',
    styleYellow: 'Maduravoyal2',
    title: 'Maduravoyal'
  },
  {
    id: 9,
    name: 'districts.Mambalam',
    blueImage: mambalamImg,
    greyImage: mambalamgreyImg,
    yellowImage: mambalam2Img,
    styleBlue: 'Mambalam',
    styleYellow: 'Mambalam2',
    title: 'Mambalam'
  },
  {
    id: 10,
    name: 'districts.Mylapore',
    blueImage: mylaporeImg,
    greyImage: mylaporegreyImg,
    yellowImage: mylapore2Img,
    styleBlue: 'Mylapore',
    styleYellow: 'Mylapore2',
    title: 'Mylapore'
  },
  {
    id: 11,
    name: 'districts.Alandur',
    blueImage: alandurImg,
    greyImage: alandurgreyImg,
    yellowImage: alandur2Img,
    styleBlue: 'Alandur',
    styleYellow: 'Alandur2',
    title: 'Alandur'
  },
  {
    id: 12,
    name: 'districts.Guindy',
    blueImage: guindyImg,
    greyImage: guindygreyImg,
    yellowImage: guindy2Img,
    styleBlue: 'Guindy',
    styleYellow: 'Guindy2',
    title: 'Guindy'
  },
  {
    id: 13,
    name: 'districts.Velacherry',
    blueImage: velacherryImg,
    greyImage: velacherrygreyImg,
    yellowImage: velacherry2Img,
    styleBlue: 'Velacherry',
    styleYellow: 'Velacherry2',
    title: 'Velachery'
  },
  {
    id: 14,
    name: 'districts.Sholinganallur',
    blueImage: sholinganallurImg,
    greyImage: sholinganallurgreyImg,
    yellowImage: sholinganallur2Img,
    styleBlue: 'Sholinganallur',
    styleYellow: 'Sholinganallur2',
    title: 'Sholinganallur'
  }
];
